name: Test Workflow

on: [push]

defaults:
  run:
    shell: bash

jobs:
  testdocker:
    runs-on: ubuntu-20.04
    
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2.3.4
    
#      - name: Cache local Maven repository
#        uses: actions/cache@v2.1.6
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
    
      - name: Get version from GITHUB_REF
        id: get_version
        run: |
          echo $GITHUB_REF
          STR=inoeg/iris-client-bff:inoeg/iris-client-bff:pr-218
          echo $STR | cut --delimiter=: --fields=2-3
          echo ${{ github.event_name }}
#          VERSION=edge
#          if [[ $GITHUB_REF == refs/tags/* ]]; then
#            VERSION=${GITHUB_REF#refs/tags/}
#          elif [[ $GITHUB_REF == refs/heads/* ]]; then
#            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
#          elif [[ $GITHUB_REF == refs/pull/* ]]; then
#            VERSION=pr-${{ github.event.number }}
#          fi
#          echo ::set-output name=version::${VERSION}
#          DOCKER_VER=$(docker --version)
#          echo $DOCKER_VER
    
