name: Test Workflow

on: [push]

defaults:
  run:
    shell: bash

jobs:
  testdocker:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
    
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      - name: Get version from GITHUB_REF
        id: get_version
        run: |
          echo $GITHUB_REF
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          echo ::set-output name=version::${VERSION}
          DOCKER_VER=$(docker --version)
          echo $DOCKER_VER
    
      - name: build, package and publish the image
        run: mvn -B clean package spring-boot:build-image -am -pl iris-client-bff -Dspring-boot.build-image.publish=true -Dversion.tag=${{ steps.get_version.outputs.version }}
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}
          
      - name: Republish with alternate tag
        run: |
          NAMESPACE=tboegner
          ARTIFACT=iris-client-bff
          TAG=dev
          TARGET=${NAMESPACE}/${ARTIFACT}:${TAG}
          echo target: $TARGET
          docker tag ${NAMESPACE}/${ARTIFACT}:${{ steps.get_version.outputs.version }} ${TARGET}
          docker push $TARGET
          
      
      

